build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

filter:
    paths:
        - 'src/*'

tools:
    external_code_coverage:
        timeout: 600
    php_loc: true
    php_pdepend: true
    php_sim: true
    php_changetracking: true
