build:
    nodes:
        php74:
            environment:
                php:
                    version: 7.4
            tests:
                override:
                    - php-scrutinizer-run
        php80:
            environment:
                php:
                    version: 8.0
            tests:
                override:
                    - php-scrutinizer-run

filter:
    paths:
        - 'src/*'

tools:
    external_code_coverage:
        timeout: 600
    php_loc: true
    php_pdepend: true
    php_sim: true
    php_changetracking: true
