build:
    environment:
        php:
            version: 8.1.12
            ini:
                xdebug.mode: off
            pecl_extensions:
                - pcov
    image: default-bionic

filter:
    paths:
        - "src/*"

tools:
    external_code_coverage:
        timeout: 600
    php_loc: true
    php_pdepend: true
    php_sim: true
    php_changetracking: true
